name: QE Continuous Integration Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  smoke-test:
    name: Smoke Test Gate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run Smoke Tests
        run: npm run test:smoke

  regression-test:
    name: Regression Test Gate
    needs: smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
       

      - name: Install dependencies
        run: npm install

      - name: Run Regression Tests
        run: npm run test:regression
